name:                git-plantation
version:             0.4.0
github:              "matsubara0507/git-plantation"
license:             MIT
author:              "MATSUBARA Nobutada"
maintainer:          "t12307043@gunma-u.ac.jp"
copyright:           "2018 MATSUBARA Nobutada"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/matsubara0507/git-plantation#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- NoImplicitPrelude

- ConstraintKinds
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- OverloadedStrings
- PolyKinds
- RankNTypes
- StandaloneDeriving
- TypeFamilies
- TypeSynonymInstances

dependencies:
- base >= 4.7 && < 5
- rio >= 0.1.1.0
- mix
- mix-json-logger
- mix-plugin-github
- mix-plugin-drone
- mix-plugin-shell
- mtl
- aeson
- blaze-html
- containers
- dotenv
- drone
- elmap
- extensible >= 0.6
- extensible-elmap
- exceptions
- fallible
- github
- github-webhooks
- http-media
- req >= 2.0
- servant-auth-server
- servant-blaze
- servant-elmap
- servant-github-webhook
- servant-server
- yaml >= 0.8.31
- http-api-data
- unliftio
- wreq
- shelly

library:
  source-dirs: src

executables:
  git-plantation-app:
    main:                Main.hs
    source-dirs:         exec/app
    dependencies:
    - git-plantation
    - gitrev
    - warp
  git-plantation-store:
    main:                Main.hs
    source-dirs:         exec/store
    dependencies:
    - git-plantation
    - gitrev
    - warp
  git-plantation-slack:
    main:                Main.hs
    source-dirs:         exec/slack
    dependencies:
    - git-plantation
    - gitrev
    - warp
  git-plantation-tool:
    main:                Main.hs
    source-dirs:         exec/tool
    dependencies:
    - git-plantation
    - gitrev
    - optparse-applicative

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test/spec
    dependencies:
    - git-plantation
    - tasty
    - tasty-hspec
    - th-lift-instances
  generateElm:
    main:                GenerateElm.hs
    source-dirs:         test
    dependencies:
    - git-plantation
    other-modules: []
