resolver: lts-15.5
packages:
- .
extra-deps:
- extensible-0.8
- membership-0
- binary-instances-1.0.0.1
- servant-github-webhook-0.4.2.0
- github-webhooks-0.12.0
- drone-1.1.0
- github: matsubara0507/github
  commit: 8224d498d289c40d3c6d0232ac571a82f8787972
- github: matsubara0507/elmap.hs
  commit: 9c9479d3ead6032a0309b5f80f42e94df85da375
  subdirs:
  - elmap
  - servant-elmap
  - extensible-elmap
- github: matsubara0507/mix.hs
  commit: a0b2b9394c340186c9a8a63808f0db1752ada4ae
  subdirs:
  - mix
  - mix-json-logger
  - mix-plugin-github
  - mix-plugin-drone
  - mix-plugin-shell
docker:
  repo: matsubara0507/stack-build
  enable: false
