resolver: lts-13.24
packages:
- .
extra-deps:
- extensible-0.5
- servant-github-webhook-0.4.1.0
- github: matsubara0507/github
  commit: e3d8f80d61e550264a82a415750e506664fdeaa2
- github: matsubara0507/drone-haskell
  commit: aa6f5152dd9ea72cb48a32bdc58c91de2bdc21a9
- github: matsubara0507/elm-export
  commit: 0a05fecf56f84aa2ad998200a03c7df2a1676c0c
- github: matsubara0507/mix.hs
  commit: 2138a7a5a43443040893134f1170ce1643f0d498
  subdirs:
  - mix
  - mix-json-logger
  - mix-plugin-github
  - mix-plugin-drone
  - mix-plugin-shell
docker:
  repo: fpco/stack-build
  enable: false
