resolver: lts-14.6
packages:
- .
extra-deps:
- extensible-0.6.1
- membership-0
- binary-instances-1
- servant-github-webhook-0.4.1.0
- github: matsubara0507/drone-haskell
  commit: d71e7473508a88922575ab95330b1e94d2114f9c
- github: matsubara0507/github
  commit: 0e53921d2433c3e86b7231e6be7d234ae75c095f
- github: matsubara0507/elmap.hs
  commit: a1539c3be6e8b5757a2a10a55e7c1b19c1fc76fd
  subdirs:
  - elmap
  - servant-elmap
  - extensible-elmap
- github: matsubara0507/mix.hs
  commit: f4cad8e116093169c8849a9ae9acefb93c3eefc5
  subdirs:
  - mix
  - mix-json-logger
  - mix-plugin-github
  - mix-plugin-drone
  - mix-plugin-shell
docker:
  repo: matsubara0507/stack-build
  enable: false
