resolver: lts-13.13
packages:
- .
extra-deps:
- extensible-0.5
- servant-github-webhook-0.4.1.0
- github: matsubara0507/github
  commit: 08f409a9cbc0ab46a3e68f84ddfb14fc89c3fe7a
- github: matsubara0507/drone-haskell
  commit: aa6f5152dd9ea72cb48a32bdc58c91de2bdc21a9
- github: matsubara0507/elm-export
  commit: 0a05fecf56f84aa2ad998200a03c7df2a1676c0c
docker:
  repo: fpco/stack-build
  enable: false
image:
  container:
    name: git-plantation-bin
    base: matsubara0507/ubuntu-for-haskell:git
