resolver: nightly-2022-04-09
packages:
- .
extra-deps:
- binary-instances-1.0.2
# - extensible-0.8.3
- github: fumieval/extensible
  commit: 4a1edb50c90d377085fcc3bad4c9f6e9d296b00e
- fallible-0.1.0
- incremental-0.3.1
- membership-0.0.1
- github: tsani/servant-github-webhook
  commit: f8cb8bc10d3e9d275fa995b0d01ba2d1eeaa700b
- github: matsubara0507/github
  commit: eaa26ad782cc9d3b19419ba7e2ebf871474eb5a8 # myext branch
- github: matsubara0507/elmap.hs
  commit: 3cd415ba620aeb588c5f7217d96a8d6f05cb45f1
  subdirs:
  - elmap
  - servant-elmap
  - extensible-elmap
- github: matsubara0507/mix.hs
  commit: da914f3c0ec152e5814ed5495c9c3aef2ceec4ed
  subdirs:
  - mix
  - mix-json-logger
  - mix-plugin-github
  - mix-plugin-persistent-sqlite
  - mix-plugin-shell
  - helper/rio-logger-ext

docker:
  repo: ghcr.io/matsubara0507/stack-build:18.04
  enable: false
