resolver: lts-13.13
packages:
- .
- ./libs/mix
- ./libs/mix-json-logger
- ./libs/mix-plugin-github
- ./libs/mix-plugin-drone
- ./libs/mix-plugin-shell
- ./libs/shh-cmd
extra-deps:
- extensible-0.5
- servant-github-webhook-0.4.1.0
- shh-0.3.1.3
- github: matsubara0507/github
  commit: 8a4fb1d8bdbb0a6ac9e017401b503e4104afb29b
- github: matsubara0507/drone-haskell
  commit: aa6f5152dd9ea72cb48a32bdc58c91de2bdc21a9
- github: matsubara0507/elm-export
  commit: 0a05fecf56f84aa2ad998200a03c7df2a1676c0c
docker:
  repo: fpco/stack-build
  enable: false
image:
  container:
    name: git-plantation-bin
    base: matsubara0507/ubuntu-for-haskell:git
