version: '2'

services:
  app:
    image: matsubara0507/git-plantation:dev
    ports:
      - 8080:8080
    volumes:
      - ./.git-plantation.yaml:/work/config.yaml
      - ./temp.sqlite:/work/temp.sqlite
    depends_on:
      - store
    restart: always
    environment:
      - PORT=8080
      - WORK=.temp
      - CONFIG=config.yaml
      - GH_TOKEN=${GH_TOKEN}
      - GH_SECRET=${GH_SECRET}
      - APP_SERVER=${APP_SERVER}
      - SLACK_API_TOKEN=${SLACK_API_TOKEN}
      - SLACK_TEAM_ID=${SLACK_TEAM_ID}
      - SLACK_CHANNEL_IDS=${SLACK_CHANNEL_IDS}
      - SLACK_RESET_REPO_CMD=/reset-repo
      - SLACK_WEBHOOK=${SLACK_WEBHOOK}
      - STORE_URL=http://store
      - AUTHN_CLIENT_ID=${AUTHN_CLIENT_ID}
      - AUTHN_CLIENT_SECRET=${AUTHN_CLIENT_SECRET}
      - SQLITE_PATH=./temp.sqlite

  store:
    image: matsubara0507/git-plantation:dev
    command: run-store.sh
    volumes:
      - ./.git-plantation.yaml:/work/config.yaml
    restart: always
    environment:
      - PORT=80
      - CONFIG=config.yaml

  runner:
    image: matsubara0507/git-plantation:dev
    command: git-plantation-runner --verbose app:8080
    deploy:
      replicas: 3
    depends_on:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
