version: '2'

services:
  scoreboard:
    image: matsubara0507/git-plantation:dev
    ports:
      - 8080:8080
    volumes:
      - ./.git-plantation.yaml:/work/config.yaml
    depends_on:
      - store
    restart: always
    environment:
      - PORT=8080
      - WORK=.temp
      - CONFIG=config.yaml
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_TOKEN=${DRONE_TOKEN}
      - DRONE_PORT=443
      - GH_TOKEN=${GH_TOKEN}
      - GH_SECRET=${GH_SECRET}
      - APP_HOST=scoreboard.git-plantation.dev
      - SLACK_API_TOKEN=${SLACK_API_TOKEN}
      - SLACK_TEAM_ID=${SLACK_TEAM_ID}
      - SLACK_CHANNEL_IDS=${SLACK_CHANNEL_IDS}
      - SLACK_RESET_REPO_CMD=/reset-repo
      - SLACK_WEBHOOK=${SLACK_WEBHOOK}
      - STORE_URL=http://store

  store:
    image: matsubara0507/git-plantation:dev
    command: run-store.sh
    volumes:
      - ./.git-plantation.yaml:/work/config.yaml
    restart: always
    environment:
      - PORT=80
      - CONFIG=config.yaml
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_TOKEN=${DRONE_TOKEN}
      - DRONE_PORT=443
