name: Build

on:
  pull_request: null
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ["8.10.4"]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: "\
          ${{ runner.os }}-stack\
          -${{ hashFiles('**/stack.yaml.lock') }}\
          -${{ hashFiles('**/package.yaml') }}\
        "
        restore-keys: |
          ${{ runner.os }}-stack-
    - uses: haskell/actions/setup@v1.2.1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: 'latest'

    - name: Install dependencies
      run: stack --system-ghc test --only-dependencies

    - name: Build and Test
      run: stack --system-ghc test --local-bin-path=./bin

    - name: Build Docker Image
      run: docker build -t git-plantation . --build-arg local_bin_path=./bin

    - name: Push Docker Image
      if: github.ref == 'refs/heads/master'
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u matsubara0507 --password-stdin
        docker tag git-plantation docker.pkg.github.com/matsubara0507/git-plantation/exe
        docker push docker.pkg.github.com/matsubara0507/git-plantation/exe:latest

    - name: Push Docker Image (tag)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u matsubara0507 --password-stdin
        docker tag git-plantation docker.pkg.github.com/matsubara0507/git-plantation/exe:${GITHUB_REF#refs/tags/}
        docker push docker.pkg.github.com/matsubara0507/git-plantation/exe:${GITHUB_REF#refs/tags/}

    - name: Display .stack size
      run: |
        du -sh ~/.stack/*
        du -sh .stack-work/*
